/*
 This file was autogenerated via
 ---------------------------------------------------
 gen-builtin --type Hex --name hex --handler AddUint
 ---------------------------------------------------
 do not touch it with bare hands!
*/

package types

var _ Field = Hex("")

// Hex represents field of type hex
type Hex string

// Name returns field name
func (i Hex) Name() string {
	return string(i)
}

// TypeName name of the type
func (i Hex) TypeName() string {
	return "hex"
}

// Register registers a field
func (i Hex) Register(registrator FieldRegistrator) {
	registrator.AddUint(i.Name())
}

// Native returns Go's representation of this field's type
func (i Hex) Native() string {
	return "hex"
}

func init() {
	if builtins == nil {
		builtins = map[string]func(name string) Field{}
	}
	builtins["hex"] = func(fieldName string) Field {
		return Hex(fieldName)
	}
}
