/*
 This file was autogenerated via
 ---------------------------------------------------------------
 gen-builtin --declarable --native --type Float64 --name float64
 ---------------------------------------------------------------
 do not touch it with bare hands!
*/

package types

var _ Field = Float64("")

// Float64 represents field of type float64
type Float64 string

// Name returns field name
func (i Float64) Name() string {
	return string(i)
}

// TypeName name of the type
func (i Float64) TypeName() string {
	return "float64"
}

// Register registers a field
func (i Float64) Register(comment []string, registrator FieldRegistrator) {
	registrator.AddFloat64(comment, i.Name())
}

// GoName returns Go's representation of this field's type
func (i Float64) GoName() string {
	return "float64"
}

func init() {
	if builtins == nil {
		builtins = map[string]func(name string) Field{}
	}
	builtins["float64"] = func(fieldName string) Field {
		return Float64(fieldName)
	}
	if natives == nil {
		natives = map[string]struct{}{}
	}
	natives["float64"] = struct{}{}
	if declarables == nil {
		declarables = map[string]struct{}{}
	}
	declarables["float64"] = struct{}{}

}
