/*
 This file was autogenerated via
 -----------------------------------
 gen-builtin --type Int8 --name int8
 -----------------------------------
 do not touch it with bare hands!
*/

package types

var _ Field = Int8("")

// Int8 represents field of type int8
type Int8 string

// Name returns field name
func (i Int8) Name() string {
	return string(i)
}

// TypeName name of the type
func (i Int8) TypeName() string {
	return "int8"
}

// Register registers a field
func (i Int8) Register(registrator FieldRegistrator) {
	registrator.AddInt8(i.Name())
}

// Native returns Go's representation of this field's type
func (i Int8) Native() string {
	return "int8"
}

func init() {
	if builtins == nil {
		builtins = map[string]func(name string) Field{}
	}
	builtins["int8"] = func(fieldName string) Field {
		return Int8(fieldName)
	}
}
