/*
 This file was autogenerated via
 ---------------------------------------------------------------------------------------
 gen-builtin --declarable --type Oct32 --name oct32 --handler AddUint32 --go-name uint32
 ---------------------------------------------------------------------------------------
 do not touch it with bare hands!
*/

package types

var _ Field = Oct32("")

// Oct32 represents field of type oct32
type Oct32 string

// Name returns field name
func (i Oct32) Name() string {
	return string(i)
}

// TypeName name of the type
func (i Oct32) TypeName() string {
	return "oct32"
}

// Register registers a field
func (i Oct32) Register(comment []string, registrator FieldRegistrator) {
	registrator.AddUint32(comment, i.Name())
}

// GoName returns Go's representation of this field's type
func (i Oct32) GoName() string {
	return "uint32"
}

func init() {
	if builtins == nil {
		builtins = map[string]func(name string) Field{}
	}
	builtins["oct32"] = func(fieldName string) Field {
		return Oct32(fieldName)
	}

	if declarables == nil {
		declarables = map[string]struct{}{}
	}
	declarables["oct32"] = struct{}{}

	if backedBy == nil {
		backedBy = map[string]string{}
	}
	backedBy["oct32"] = "uint32"
}
