/*
 This file was autogenerated via
 -------------------------------------------------------------
 gen-builtin --declarable --native --type Uint64 --name uint64
 -------------------------------------------------------------
 do not touch it with bare hands!
*/

package types

var _ Field = Uint64("")

// Uint64 represents field of type uint64
type Uint64 string

// Name returns field name
func (i Uint64) Name() string {
	return string(i)
}

// TypeName name of the type
func (i Uint64) TypeName() string {
	return "uint64"
}

// Register registers a field
func (i Uint64) Register(registrator FieldRegistrator) {
	registrator.AddUint64(i.Name())
}

// GoName returns Go's representation of this field's type
func (i Uint64) GoName() string {
	return "uint64"
}

func init() {
	if builtins == nil {
		builtins = map[string]func(name string) Field{}
	}
	builtins["uint64"] = func(fieldName string) Field {
		return Uint64(fieldName)
	}
	if natives == nil {
		natives = map[string]struct{}{}
	}
	natives["uint64"] = struct{}{}
	if declarables == nil {
		declarables = map[string]struct{}{}
	}
	declarables["uint64"] = struct{}{}

}
