/*
 This file was autogenerated via
 ---------------------------------------------------------------------------------------
 gen-builtin --declarable --type Hex32 --name hex32 --handler AddUint32 --go-name uint32
 ---------------------------------------------------------------------------------------
 do not touch it with bare hands!
*/

package types

var _ Field = Hex32("")

// Hex32 represents field of type hex32
type Hex32 string

// Name returns field name
func (i Hex32) Name() string {
	return string(i)
}

// TypeName name of the type
func (i Hex32) TypeName() string {
	return "hex32"
}

// Register registers a field
func (i Hex32) Register(comment []string, registrator FieldRegistrator) {
	registrator.AddUint32(comment, i.Name())
}

// GoName returns Go's representation of this field's type
func (i Hex32) GoName() string {
	return "uint32"
}

func init() {
	if builtins == nil {
		builtins = map[string]func(name string) Field{}
	}
	builtins["hex32"] = func(fieldName string) Field {
		return Hex32(fieldName)
	}

	if declarables == nil {
		declarables = map[string]struct{}{}
	}
	declarables["hex32"] = struct{}{}

	if backedBy == nil {
		backedBy = map[string]string{}
	}
	backedBy["hex32"] = "uint32"
}
