/*
 This file was autogenerated via
 -------------------------------------
 gen-builtin --type Int64 --name int64
 -------------------------------------
 do not touch it with bare hands!
*/

package types

var _ Field = Int64("")

// Int64 represents field of type int64
type Int64 string

// Name returns field name
func (i Int64) Name() string {
	return string(i)
}

// TypeName name of the type
func (i Int64) TypeName() string {
	return "int64"
}

// Register registers a field
func (i Int64) Register(registrator FieldRegistrator) {
	registrator.AddInt64(i.Name())
}

// Native returns Go's representation of this field's type
func (i Int64) Native() string {
	return "int64"
}

func init() {
	if builtins == nil {
		builtins = map[string]func(name string) Field{}
	}
	builtins["int64"] = func(fieldName string) Field {
		return Int64(fieldName)
	}
}
