/*
 This file was autogenerated via
 --------------------------------------------------------
 gen-builtin --type Dec64 --name dec64 --handler AddInt64
 --------------------------------------------------------
 do not touch it with bare hands!
*/

package types

var _ Field = Dec64("")

// Dec64 represents field of type dec64
type Dec64 string

// Name returns field name
func (i Dec64) Name() string {
	return string(i)
}

// TypeName name of the type
func (i Dec64) TypeName() string {
	return "dec64"
}

// Register registers a field
func (i Dec64) Register(registrator FieldRegistrator) {
	registrator.AddInt64(i.Name())
}

// Native returns Go's representation of this field's type
func (i Dec64) Native() string {
	return "dec64"
}

func init() {
	if builtins == nil {
		builtins = map[string]func(name string) Field{}
	}
	builtins["dec64"] = func(fieldName string) Field {
		return Dec64(fieldName)
	}
}
