/*
 This file was autogenerated via
 -----------------------------------
 gen-builtin --type Uint --name uint
 -----------------------------------
 do not touch it with bare hands!
*/

package types

var _ Field = Uint("")

// Uint represents field of type uint
type Uint string

// Name returns field name
func (i Uint) Name() string {
	return string(i)
}

// TypeName name of the type
func (i Uint) TypeName() string {
	return "uint"
}

// Register registers a field
func (i Uint) Register(registrator FieldRegistrator) {
	registrator.AddUint(i.Name())
}

// Native returns Go's representation of this field's type
func (i Uint) Native() string {
	return "uint"
}

func init() {
	if builtins == nil {
		builtins = map[string]func(name string) Field{}
	}
	builtins["uint"] = func(fieldName string) Field {
		return Uint(fieldName)
	}
}
