/*
 This file was autogenerated via
 ------------------------------------------------------
 gen-builtin --type Hex8 --name hex8 --handler AddUint8
 ------------------------------------------------------
 do not touch it with bare hands!
*/

package types

var _ Field = Hex8("")

// Hex8 represents field of type hex8
type Hex8 string

// Name returns field name
func (i Hex8) Name() string {
	return string(i)
}

// TypeName name of the type
func (i Hex8) TypeName() string {
	return "hex8"
}

// Register registers a field
func (i Hex8) Register(registrator FieldRegistrator) {
	registrator.AddUint8(i.Name())
}

// Native returns Go's representation of this field's type
func (i Hex8) Native() string {
	return "hex8"
}

func init() {
	if builtins == nil {
		builtins = map[string]func(name string) Field{}
	}
	builtins["hex8"] = func(fieldName string) Field {
		return Hex8(fieldName)
	}
}
