/*
 This file was autogenerated via
 --------------------------------------------------------------------------------
 gen-builtin --type Dec128 --name dec128 --native struct { Lo uint64; Hi uint64 }
 --------------------------------------------------------------------------------
 do not touch it with bare hands!
*/

package types

var _ Field = Dec128("")

// Dec128 represents field of type dec128
type Dec128 string

// Name returns field name
func (i Dec128) Name() string {
	return string(i)
}

// TypeName name of the type
func (i Dec128) TypeName() string {
	return "dec128"
}

// Register registers a field
func (i Dec128) Register(registrator FieldRegistrator) {
	registrator.AddDec128(i.Name())
}

// Native returns Go's representation of this field's type
func (i Dec128) Native() string {
	return "struct { Lo uint64; Hi uint64 }"
}

func init() {
	if builtins == nil {
		builtins = map[string]func(name string) Field{}
	}
	builtins["dec128"] = func(fieldName string) Field {
		return Dec128(fieldName)
	}
}
