/*
 This file was autogenerated via
 ---------------------------------------------------------------------------------------
 gen-builtin --declarable --type Oct16 --name oct16 --handler AddUint16 --go-name uint16
 ---------------------------------------------------------------------------------------
 do not touch it with bare hands!
*/

package types

var _ Field = Oct16("")

// Oct16 represents field of type oct16
type Oct16 string

// Name returns field name
func (i Oct16) Name() string {
	return string(i)
}

// TypeName name of the type
func (i Oct16) TypeName() string {
	return "oct16"
}

// Register registers a field
func (i Oct16) Register(registrator FieldRegistrator) {
	registrator.AddUint16(i.Name())
}

// GoName returns Go's representation of this field's type
func (i Oct16) GoName() string {
	return "uint16"
}

func init() {
	if builtins == nil {
		builtins = map[string]func(name string) Field{}
	}
	builtins["oct16"] = func(fieldName string) Field {
		return Oct16(fieldName)
	}

	if declarables == nil {
		declarables = map[string]struct{}{}
	}
	declarables["oct16"] = struct{}{}

	if backedBy == nil {
		backedBy = map[string]string{}
	}
	backedBy["oct16"] = "uint16"
}
