/*
 This file was autogenerated via
 -----------------------------------------
 gen-builtin --type Float32 --name float32
 -----------------------------------------
 do not touch it with bare hands!
*/

package types

var _ Field = Float32("")

// Float32 represents field of type float32
type Float32 string

// Name returns field name
func (i Float32) Name() string {
	return string(i)
}

// TypeName name of the type
func (i Float32) TypeName() string {
	return "float32"
}

// Register registers a field
func (i Float32) Register(registrator FieldRegistrator) {
	registrator.AddFloat32(i.Name())
}

// Native returns Go's representation of this field's type
func (i Float32) Native() string {
	return "float32"
}

func init() {
	if builtins == nil {
		builtins = map[string]func(name string) Field{}
	}
	builtins["float32"] = func(fieldName string) Field {
		return Float32(fieldName)
	}
}
