
// Code generated by gocc; DO NOT EDIT.

package lexer



/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates] func(rune) int

var TransTab = TransitionTable{
	
		// S0
		func(r rune) int {
			switch {
			case r == 9 : // ['\t','\t']
				return 1
			case r == 10 : // ['\n','\n']
				return 1
			case r == 13 : // ['\r','\r']
				return 1
			case r == 32 : // [' ',' ']
				return 1
			case r == 33 : // ['!','!']
				return 2
			case r == 34 : // ['"','"']
				return 3
			case r == 35 : // ['#','#']
				return 4
			case r == 36 : // ['$','$']
				return 5
			case r == 39 : // [''',''']
				return 6
			case r == 40 : // ['(','(']
				return 7
			case r == 41 : // [')',')']
				return 8
			case 48 <= r && r <= 57 : // ['0','9']
				return 9
			case r == 58 : // [':',':']
				return 10
			case r == 59 : // [';',';']
				return 11
			case r == 61 : // ['=','=']
				return 12
			case r == 63 : // ['?','?']
				return 13
			case 65 <= r && r <= 90 : // ['A','Z']
				return 14
			case r == 91 : // ['[','[']
				return 15
			case r == 93 : // [']',']']
				return 16
			case r == 94 : // ['^','^']
				return 17
			case r == 95 : // ['_','_']
				return 18
			case 97 <= r && r <= 122 : // ['a','z']
				return 14
			
			
			
			}
			return NoState
		},
	
		// S1
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
		},
	
		// S2
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
		},
	
		// S3
		func(r rune) int {
			switch {
			case r == 34 : // ['"','"']
				return 19
			case r == 92 : // ['\','\']
				return 20
			
			
			default:
				return 21
			}
			
		},
	
		// S4
		func(r rune) int {
			switch {
			case r == 10 : // ['\n','\n']
				return 22
			
			
			default:
				return 4
			}
			
		},
	
		// S5
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
		},
	
		// S6
		func(r rune) int {
			switch {
			case r == 92 : // ['\','\']
				return 23
			
			
			default:
				return 24
			}
			
		},
	
		// S7
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
		},
	
		// S8
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
		},
	
		// S9
		func(r rune) int {
			switch {
			case 48 <= r && r <= 57 : // ['0','9']
				return 9
			
			
			
			}
			return NoState
		},
	
		// S10
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
		},
	
		// S11
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
		},
	
		// S12
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
		},
	
		// S13
		func(r rune) int {
			switch {
			case r == 63 : // ['?','?']
				return 25
			
			
			
			}
			return NoState
		},
	
		// S14
		func(r rune) int {
			switch {
			case 48 <= r && r <= 57 : // ['0','9']
				return 26
			case 65 <= r && r <= 90 : // ['A','Z']
				return 14
			case r == 95 : // ['_','_']
				return 14
			case 97 <= r && r <= 122 : // ['a','z']
				return 14
			
			
			
			}
			return NoState
		},
	
		// S15
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
		},
	
		// S16
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
		},
	
		// S17
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
		},
	
		// S18
		func(r rune) int {
			switch {
			case 48 <= r && r <= 57 : // ['0','9']
				return 26
			case 65 <= r && r <= 90 : // ['A','Z']
				return 14
			case r == 95 : // ['_','_']
				return 14
			case 97 <= r && r <= 122 : // ['a','z']
				return 14
			
			
			
			}
			return NoState
		},
	
		// S19
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
		},
	
		// S20
		func(r rune) int {
			switch {
			case r == 34 : // ['"','"']
				return 27
			case r == 48 : // ['0','0']
				return 27
			case r == 92 : // ['\','\']
				return 27
			case r == 97 : // ['a','a']
				return 27
			case r == 98 : // ['b','b']
				return 27
			case r == 110 : // ['n','n']
				return 27
			case r == 114 : // ['r','r']
				return 27
			case r == 116 : // ['t','t']
				return 27
			
			
			
			}
			return NoState
		},
	
		// S21
		func(r rune) int {
			switch {
			case r == 34 : // ['"','"']
				return 19
			case r == 92 : // ['\','\']
				return 20
			
			
			default:
				return 21
			}
			
		},
	
		// S22
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
		},
	
		// S23
		func(r rune) int {
			switch {
			case r == 39 : // [''',''']
				return 28
			case r == 48 : // ['0','0']
				return 28
			case r == 92 : // ['\','\']
				return 28
			case r == 97 : // ['a','a']
				return 28
			case r == 98 : // ['b','b']
				return 28
			case r == 110 : // ['n','n']
				return 28
			case r == 114 : // ['r','r']
				return 28
			case r == 116 : // ['t','t']
				return 28
			
			
			
			}
			return NoState
		},
	
		// S24
		func(r rune) int {
			switch {
			case r == 39 : // [''',''']
				return 29
			
			
			
			}
			return NoState
		},
	
		// S25
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
		},
	
		// S26
		func(r rune) int {
			switch {
			case 48 <= r && r <= 57 : // ['0','9']
				return 26
			case 65 <= r && r <= 90 : // ['A','Z']
				return 14
			case r == 95 : // ['_','_']
				return 14
			case 97 <= r && r <= 122 : // ['a','z']
				return 14
			
			
			
			}
			return NoState
		},
	
		// S27
		func(r rune) int {
			switch {
			case r == 34 : // ['"','"']
				return 19
			case r == 92 : // ['\','\']
				return 20
			
			
			default:
				return 21
			}
			
		},
	
		// S28
		func(r rune) int {
			switch {
			case r == 39 : // [''',''']
				return 29
			
			
			
			}
			return NoState
		},
	
		// S29
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
		},
	
}
