
/*
 This file was autogenerated via
 -----------------------------------------------------------
 ldetool --package ldetesting --go-string missing_import.lde
 -----------------------------------------------------------
 do not touch it with bare hands!
*/

package ldetesting

import (
	"fmt"
	"strings"
	time "time"
)

// ShouldBeImportWithCustomType ...
type ShouldBeImportWithCustomType struct {
	Rest   string
	First  time.Time
	Second time.Time
}

// Extract ...
func (p *ShouldBeImportWithCustomType) Extract(line string) (bool, error) {
	p.Rest = line
	var err error
	var pos int
	var tmp string

	// Take until ':' as First(time.Time)
	pos = strings.IndexByte(p.Rest, ':')
	if pos >= 0 {
		tmp = p.Rest[:pos]
		p.Rest = p.Rest[pos+1:]
	} else {
		return false, nil
	}
	if p.First, err = p.unmarshalFirst(tmp); err != nil {
		return false, fmt.Errorf("parsing `%s` into field First(time.Time): %s", tmp, err)
	}

	// Take the rest as Second(time.Time)
	if p.Second, err = p.unmarshalSecond(p.Rest); err != nil {
		return false, fmt.Errorf("parsing `%s` into field Second(time.Time): %s", p.Rest, err)
	}
	p.Rest = p.Rest[len(p.Rest):]
	return true, nil
}
