
// Code generated by gocc; DO NOT EDIT.

package parser

type(
	actionTable [numStates]actionRow
	actionRow struct {
		canRecover bool
		actions [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			shift(3),		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			accept(true),		/* $ */
			shift(3),		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(2),		/* $, reduce: Rules */
			reduce(2),		/* identifier, reduce: Rules */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			shift(5),		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(1),		/* $, reduce: Rules */
			reduce(1),		/* identifier, reduce: Rules */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			shift(6),		/* $ */
			shift(7),		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			shift(9),		/* ( */
			nil,		/* ) */
			shift(11),		/* stress */
			shift(12),		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			shift(13),		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			shift(14),		/* ? */
			
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(18),		/* $, reduce: AtomicAction */
			reduce(18),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			reduce(18),		/* ;, reduce: AtomicAction */
			reduce(18),		/* (, reduce: AtomicAction */
			nil,		/* ) */
			reduce(18),		/* stress, reduce: AtomicAction */
			reduce(18),		/* ^, reduce: AtomicAction */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(18),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(18),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			shift(15),		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			shift(16),		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			shift(17),		/* $ */
			shift(18),		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			shift(20),		/* ( */
			nil,		/* ) */
			shift(22),		/* stress */
			shift(23),		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			shift(24),		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			shift(25),		/* ? */
			
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			shift(6),		/* $ */
			shift(7),		/* identifier */
			nil,		/* = */
			reduce(7),		/* ;, reduce: Action */
			shift(9),		/* ( */
			nil,		/* ) */
			shift(11),		/* stress */
			shift(12),		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			shift(13),		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			shift(14),		/* ? */
			
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			shift(6),		/* $ */
			shift(7),		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			shift(9),		/* ( */
			nil,		/* ) */
			shift(11),		/* stress */
			shift(12),		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			shift(13),		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			shift(14),		/* ? */
			
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			shift(28),		/* string_lit */
			shift(29),		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			shift(30),		/* string_lit */
			shift(31),		/* char_lit */
			nil,		/* _ */
			shift(32),		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			shift(34),		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			shift(35),		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(3),		/* $, reduce: Rule */
			reduce(3),		/* identifier, reduce: Rule */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(18),		/* $, reduce: AtomicAction */
			reduce(18),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			nil,		/* ; */
			reduce(18),		/* (, reduce: AtomicAction */
			reduce(18),		/* ), reduce: AtomicAction */
			reduce(18),		/* stress, reduce: AtomicAction */
			reduce(18),		/* ^, reduce: AtomicAction */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(18),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(18),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			shift(36),		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			shift(37),		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			shift(17),		/* $ */
			shift(18),		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			shift(20),		/* ( */
			nil,		/* ) */
			shift(22),		/* stress */
			shift(23),		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			shift(24),		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			shift(25),		/* ? */
			
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			shift(17),		/* $ */
			shift(18),		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			shift(20),		/* ( */
			reduce(7),		/* ), reduce: Action */
			shift(22),		/* stress */
			shift(23),		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			shift(24),		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			shift(25),		/* ? */
			
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			shift(17),		/* $ */
			shift(18),		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			shift(20),		/* ( */
			nil,		/* ) */
			shift(22),		/* stress */
			shift(23),		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			shift(24),		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			shift(25),		/* ? */
			
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			shift(41),		/* string_lit */
			shift(42),		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			shift(43),		/* string_lit */
			shift(44),		/* char_lit */
			nil,		/* _ */
			shift(45),		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			shift(47),		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			reduce(6),		/* ;, reduce: Action */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			reduce(8),		/* ;, reduce: Action */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(9),		/* $, reduce: AtomicAction */
			reduce(9),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			reduce(9),		/* ;, reduce: AtomicAction */
			reduce(9),		/* (, reduce: AtomicAction */
			nil,		/* ) */
			reduce(9),		/* stress, reduce: AtomicAction */
			reduce(9),		/* ^, reduce: AtomicAction */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(9),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(9),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(10),		/* $, reduce: AtomicAction */
			reduce(10),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			reduce(10),		/* ;, reduce: AtomicAction */
			reduce(10),		/* (, reduce: AtomicAction */
			nil,		/* ) */
			reduce(10),		/* stress, reduce: AtomicAction */
			reduce(10),		/* ^, reduce: AtomicAction */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(10),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(10),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(21),		/* $, reduce: Target */
			reduce(21),		/* identifier, reduce: Target */
			nil,		/* = */
			reduce(21),		/* ;, reduce: Target */
			reduce(21),		/* (, reduce: Target */
			nil,		/* ) */
			reduce(21),		/* stress, reduce: Target */
			reduce(21),		/* ^, reduce: Target */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(21),		/* _, reduce: Target */
			shift(48),		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(21),		/* ?, reduce: Target */
			
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(24),		/* $, reduce: Target */
			reduce(24),		/* identifier, reduce: Target */
			nil,		/* = */
			reduce(24),		/* ;, reduce: Target */
			reduce(24),		/* (, reduce: Target */
			nil,		/* ) */
			reduce(24),		/* stress, reduce: Target */
			reduce(24),		/* ^, reduce: Target */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(24),		/* _, reduce: Target */
			shift(49),		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(24),		/* ?, reduce: Target */
			
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			shift(50),		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(12),		/* $, reduce: AtomicAction */
			reduce(12),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			reduce(12),		/* ;, reduce: AtomicAction */
			reduce(12),		/* (, reduce: AtomicAction */
			nil,		/* ) */
			reduce(12),		/* stress, reduce: AtomicAction */
			reduce(12),		/* ^, reduce: AtomicAction */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(12),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(12),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			shift(51),		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			shift(52),		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			shift(53),		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			shift(6),		/* $ */
			shift(7),		/* identifier */
			nil,		/* = */
			reduce(5),		/* ;, reduce: Action */
			shift(9),		/* ( */
			nil,		/* ) */
			shift(11),		/* stress */
			shift(12),		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			shift(13),		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			shift(14),		/* ? */
			
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			shift(55),		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			reduce(6),		/* ), reduce: Action */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			reduce(8),		/* ), reduce: Action */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(9),		/* $, reduce: AtomicAction */
			reduce(9),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			nil,		/* ; */
			reduce(9),		/* (, reduce: AtomicAction */
			reduce(9),		/* ), reduce: AtomicAction */
			reduce(9),		/* stress, reduce: AtomicAction */
			reduce(9),		/* ^, reduce: AtomicAction */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(9),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(9),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(10),		/* $, reduce: AtomicAction */
			reduce(10),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			nil,		/* ; */
			reduce(10),		/* (, reduce: AtomicAction */
			reduce(10),		/* ), reduce: AtomicAction */
			reduce(10),		/* stress, reduce: AtomicAction */
			reduce(10),		/* ^, reduce: AtomicAction */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(10),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(10),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(21),		/* $, reduce: Target */
			reduce(21),		/* identifier, reduce: Target */
			nil,		/* = */
			nil,		/* ; */
			reduce(21),		/* (, reduce: Target */
			reduce(21),		/* ), reduce: Target */
			reduce(21),		/* stress, reduce: Target */
			reduce(21),		/* ^, reduce: Target */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(21),		/* _, reduce: Target */
			shift(56),		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(21),		/* ?, reduce: Target */
			
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(24),		/* $, reduce: Target */
			reduce(24),		/* identifier, reduce: Target */
			nil,		/* = */
			nil,		/* ; */
			reduce(24),		/* (, reduce: Target */
			reduce(24),		/* ), reduce: Target */
			reduce(24),		/* stress, reduce: Target */
			reduce(24),		/* ^, reduce: Target */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(24),		/* _, reduce: Target */
			shift(57),		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(24),		/* ?, reduce: Target */
			
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			shift(58),		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(12),		/* $, reduce: AtomicAction */
			reduce(12),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			nil,		/* ; */
			reduce(12),		/* (, reduce: AtomicAction */
			reduce(12),		/* ), reduce: AtomicAction */
			reduce(12),		/* stress, reduce: AtomicAction */
			reduce(12),		/* ^, reduce: AtomicAction */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(12),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(12),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			shift(59),		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			shift(60),		/* int_lit */
			shift(61),		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			shift(62),		/* int_lit */
			shift(63),		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			shift(64),		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			shift(17),		/* $ */
			shift(18),		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			shift(20),		/* ( */
			nil,		/* ) */
			shift(22),		/* stress */
			shift(23),		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			shift(24),		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			shift(25),		/* ? */
			
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(17),		/* $, reduce: AtomicAction */
			reduce(17),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			reduce(17),		/* ;, reduce: AtomicAction */
			reduce(17),		/* (, reduce: AtomicAction */
			nil,		/* ) */
			reduce(17),		/* stress, reduce: AtomicAction */
			reduce(17),		/* ^, reduce: AtomicAction */
			shift(30),		/* string_lit */
			shift(31),		/* char_lit */
			reduce(17),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			shift(67),		/* ?? */
			reduce(17),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			shift(68),		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			reduce(4),		/* ;, reduce: Action */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			shift(17),		/* $ */
			shift(18),		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			shift(20),		/* ( */
			reduce(5),		/* ), reduce: Action */
			shift(22),		/* stress */
			shift(23),		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			shift(24),		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			shift(25),		/* ? */
			
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			shift(70),		/* int_lit */
			shift(71),		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S57
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			shift(72),		/* int_lit */
			shift(73),		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S58
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			shift(74),		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S59
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			shift(17),		/* $ */
			shift(18),		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			shift(20),		/* ( */
			nil,		/* ) */
			shift(22),		/* stress */
			shift(23),		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			shift(24),		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			shift(25),		/* ? */
			
		},
	},
	actionRow{ // S60
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			shift(76),		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S61
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			shift(77),		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S62
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			shift(78),		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S63
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			shift(79),		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S64
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			shift(80),		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S65
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			shift(81),		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S66
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(15),		/* $, reduce: AtomicAction */
			reduce(15),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			reduce(15),		/* ;, reduce: AtomicAction */
			reduce(15),		/* (, reduce: AtomicAction */
			nil,		/* ) */
			reduce(15),		/* stress, reduce: AtomicAction */
			reduce(15),		/* ^, reduce: AtomicAction */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(15),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(15),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S67
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			shift(82),		/* string_lit */
			shift(83),		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S68
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(17),		/* $, reduce: AtomicAction */
			reduce(17),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			nil,		/* ; */
			reduce(17),		/* (, reduce: AtomicAction */
			reduce(17),		/* ), reduce: AtomicAction */
			reduce(17),		/* stress, reduce: AtomicAction */
			reduce(17),		/* ^, reduce: AtomicAction */
			shift(43),		/* string_lit */
			shift(44),		/* char_lit */
			reduce(17),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			shift(85),		/* ?? */
			reduce(17),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S69
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			reduce(4),		/* ), reduce: Action */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S70
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			shift(86),		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S71
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			shift(87),		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S72
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			shift(88),		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S73
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			shift(89),		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S74
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			shift(90),		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S75
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			shift(91),		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S76
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			shift(92),		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S77
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			shift(93),		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S78
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			shift(94),		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S79
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			shift(95),		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S80
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(11),		/* $, reduce: AtomicAction */
			reduce(11),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			reduce(11),		/* ;, reduce: AtomicAction */
			reduce(11),		/* (, reduce: AtomicAction */
			nil,		/* ) */
			reduce(11),		/* stress, reduce: AtomicAction */
			reduce(11),		/* ^, reduce: AtomicAction */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(11),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(11),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S81
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(16),		/* $, reduce: AtomicAction */
			reduce(16),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			reduce(16),		/* ;, reduce: AtomicAction */
			reduce(16),		/* (, reduce: AtomicAction */
			nil,		/* ) */
			reduce(16),		/* stress, reduce: AtomicAction */
			reduce(16),		/* ^, reduce: AtomicAction */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(16),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(16),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S82
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(13),		/* $, reduce: AtomicAction */
			reduce(13),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			reduce(13),		/* ;, reduce: AtomicAction */
			reduce(13),		/* (, reduce: AtomicAction */
			nil,		/* ) */
			reduce(13),		/* stress, reduce: AtomicAction */
			reduce(13),		/* ^, reduce: AtomicAction */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(13),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(13),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S83
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(14),		/* $, reduce: AtomicAction */
			reduce(14),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			reduce(14),		/* ;, reduce: AtomicAction */
			reduce(14),		/* (, reduce: AtomicAction */
			nil,		/* ) */
			reduce(14),		/* stress, reduce: AtomicAction */
			reduce(14),		/* ^, reduce: AtomicAction */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(14),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(14),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S84
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(15),		/* $, reduce: AtomicAction */
			reduce(15),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			nil,		/* ; */
			reduce(15),		/* (, reduce: AtomicAction */
			reduce(15),		/* ), reduce: AtomicAction */
			reduce(15),		/* stress, reduce: AtomicAction */
			reduce(15),		/* ^, reduce: AtomicAction */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(15),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(15),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S85
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			shift(96),		/* string_lit */
			shift(97),		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S86
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			shift(98),		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S87
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			shift(99),		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S88
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			shift(100),		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S89
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			shift(101),		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S90
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(11),		/* $, reduce: AtomicAction */
			reduce(11),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			nil,		/* ; */
			reduce(11),		/* (, reduce: AtomicAction */
			reduce(11),		/* ), reduce: AtomicAction */
			reduce(11),		/* stress, reduce: AtomicAction */
			reduce(11),		/* ^, reduce: AtomicAction */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(11),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(11),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S91
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(16),		/* $, reduce: AtomicAction */
			reduce(16),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			nil,		/* ; */
			reduce(16),		/* (, reduce: AtomicAction */
			reduce(16),		/* ), reduce: AtomicAction */
			reduce(16),		/* stress, reduce: AtomicAction */
			reduce(16),		/* ^, reduce: AtomicAction */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(16),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(16),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S92
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			shift(102),		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S93
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(19),		/* $, reduce: Target */
			reduce(19),		/* identifier, reduce: Target */
			nil,		/* = */
			reduce(19),		/* ;, reduce: Target */
			reduce(19),		/* (, reduce: Target */
			nil,		/* ) */
			reduce(19),		/* stress, reduce: Target */
			reduce(19),		/* ^, reduce: Target */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(19),		/* _, reduce: Target */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(19),		/* ?, reduce: Target */
			
		},
	},
	actionRow{ // S94
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			shift(103),		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S95
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(22),		/* $, reduce: Target */
			reduce(22),		/* identifier, reduce: Target */
			nil,		/* = */
			reduce(22),		/* ;, reduce: Target */
			reduce(22),		/* (, reduce: Target */
			nil,		/* ) */
			reduce(22),		/* stress, reduce: Target */
			reduce(22),		/* ^, reduce: Target */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(22),		/* _, reduce: Target */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(22),		/* ?, reduce: Target */
			
		},
	},
	actionRow{ // S96
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(13),		/* $, reduce: AtomicAction */
			reduce(13),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			nil,		/* ; */
			reduce(13),		/* (, reduce: AtomicAction */
			reduce(13),		/* ), reduce: AtomicAction */
			reduce(13),		/* stress, reduce: AtomicAction */
			reduce(13),		/* ^, reduce: AtomicAction */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(13),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(13),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S97
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(14),		/* $, reduce: AtomicAction */
			reduce(14),		/* identifier, reduce: AtomicAction */
			nil,		/* = */
			nil,		/* ; */
			reduce(14),		/* (, reduce: AtomicAction */
			reduce(14),		/* ), reduce: AtomicAction */
			reduce(14),		/* stress, reduce: AtomicAction */
			reduce(14),		/* ^, reduce: AtomicAction */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(14),		/* _, reduce: AtomicAction */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(14),		/* ?, reduce: AtomicAction */
			
		},
	},
	actionRow{ // S98
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			shift(104),		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S99
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(19),		/* $, reduce: Target */
			reduce(19),		/* identifier, reduce: Target */
			nil,		/* = */
			nil,		/* ; */
			reduce(19),		/* (, reduce: Target */
			reduce(19),		/* ), reduce: Target */
			reduce(19),		/* stress, reduce: Target */
			reduce(19),		/* ^, reduce: Target */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(19),		/* _, reduce: Target */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(19),		/* ?, reduce: Target */
			
		},
	},
	actionRow{ // S100
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* identifier */
			nil,		/* = */
			nil,		/* ; */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* stress */
			nil,		/* ^ */
			nil,		/* string_lit */
			nil,		/* char_lit */
			nil,		/* _ */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			shift(105),		/* ] */
			nil,		/* ?? */
			nil,		/* ? */
			
		},
	},
	actionRow{ // S101
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(22),		/* $, reduce: Target */
			reduce(22),		/* identifier, reduce: Target */
			nil,		/* = */
			nil,		/* ; */
			reduce(22),		/* (, reduce: Target */
			reduce(22),		/* ), reduce: Target */
			reduce(22),		/* stress, reduce: Target */
			reduce(22),		/* ^, reduce: Target */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(22),		/* _, reduce: Target */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(22),		/* ?, reduce: Target */
			
		},
	},
	actionRow{ // S102
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(20),		/* $, reduce: Target */
			reduce(20),		/* identifier, reduce: Target */
			nil,		/* = */
			reduce(20),		/* ;, reduce: Target */
			reduce(20),		/* (, reduce: Target */
			nil,		/* ) */
			reduce(20),		/* stress, reduce: Target */
			reduce(20),		/* ^, reduce: Target */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(20),		/* _, reduce: Target */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(20),		/* ?, reduce: Target */
			
		},
	},
	actionRow{ // S103
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(23),		/* $, reduce: Target */
			reduce(23),		/* identifier, reduce: Target */
			nil,		/* = */
			reduce(23),		/* ;, reduce: Target */
			reduce(23),		/* (, reduce: Target */
			nil,		/* ) */
			reduce(23),		/* stress, reduce: Target */
			reduce(23),		/* ^, reduce: Target */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(23),		/* _, reduce: Target */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(23),		/* ?, reduce: Target */
			
		},
	},
	actionRow{ // S104
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(20),		/* $, reduce: Target */
			reduce(20),		/* identifier, reduce: Target */
			nil,		/* = */
			nil,		/* ; */
			reduce(20),		/* (, reduce: Target */
			reduce(20),		/* ), reduce: Target */
			reduce(20),		/* stress, reduce: Target */
			reduce(20),		/* ^, reduce: Target */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(20),		/* _, reduce: Target */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(20),		/* ?, reduce: Target */
			
		},
	},
	actionRow{ // S105
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(23),		/* $, reduce: Target */
			reduce(23),		/* identifier, reduce: Target */
			nil,		/* = */
			nil,		/* ; */
			reduce(23),		/* (, reduce: Target */
			reduce(23),		/* ), reduce: Target */
			reduce(23),		/* stress, reduce: Target */
			reduce(23),		/* ^, reduce: Target */
			nil,		/* string_lit */
			nil,		/* char_lit */
			reduce(23),		/* _, reduce: Target */
			nil,		/* [ */
			nil,		/* int_lit */
			nil,		/* : */
			nil,		/* ] */
			nil,		/* ?? */
			reduce(23),		/* ?, reduce: Target */
			
		},
	},
	
}

