// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 7

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Rules
		2,  // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Rules
		4,  // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Rules
		-1, // Rule
		8,  // Action
		-1, // Type
		10, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Rules
		-1, // Rule
		19, // Action
		-1, // Type
		21, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Rules
		-1, // Rule
		26, // Action
		-1, // Type
		10, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Rules
		-1, // Rule
		27, // Action
		-1, // Type
		10, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		35, // Target
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		37, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Rules
		-1, // Rule
		51, // Action
		-1, // Type
		21, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Rules
		-1, // Rule
		52, // Action
		-1, // Type
		21, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Rules
		-1, // Rule
		53, // Action
		-1, // Type
		21, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		61, // Target
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S33
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		67, // Target
	},
	gotoRow{ // S34
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S35
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S36
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S37
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S38
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S39
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S40
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S41
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S42
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S43
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S44
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S45
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S46
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S47
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S48
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S49
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		71, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S50
		-1, // S'
		-1, // Rules
		-1, // Rule
		72, // Action
		-1, // Type
		10, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S51
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S52
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S53
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S54
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S55
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S56
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S57
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S58
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S59
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		78, // Target
	},
	gotoRow{ // S60
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S61
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S62
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S63
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S64
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S65
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S66
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S67
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S68
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S69
		-1, // S'
		-1, // Rules
		-1, // Rule
		88, // Action
		-1, // Type
		21, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S70
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		90, // Target
	},
	gotoRow{ // S71
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S72
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S73
		-1, // S'
		-1, // Rules
		-1, // Rule
		92, // Action
		-1, // Type
		21, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S74
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S75
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S76
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S77
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S78
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S79
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S80
		-1,  // S'
		-1,  // Rules
		-1,  // Rule
		100, // Action
		-1,  // Type
		21,  // AtomicAction
		-1,  // Target
	},
	gotoRow{ // S81
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S82
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S83
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S84
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S85
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S86
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S87
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S88
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S89
		-1,  // S'
		-1,  // Rules
		-1,  // Rule
		-1,  // Action
		-1,  // Type
		-1,  // AtomicAction
		109, // Target
	},
	gotoRow{ // S90
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S91
		-1,  // S'
		-1,  // Rules
		-1,  // Rule
		-1,  // Action
		-1,  // Type
		-1,  // AtomicAction
		111, // Target
	},
	gotoRow{ // S92
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S93
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S94
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S95
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S96
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S97
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S98
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S99
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S100
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S101
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S102
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S103
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S104
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S105
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S106
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S107
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S108
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S109
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S110
		-1,  // S'
		-1,  // Rules
		-1,  // Rule
		-1,  // Action
		-1,  // Type
		-1,  // AtomicAction
		124, // Target
	},
	gotoRow{ // S111
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S112
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S113
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S114
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S115
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S116
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S117
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S118
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S119
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S120
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S121
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S122
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S123
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S124
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S125
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S126
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S127
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S128
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S129
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S130
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S131
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
	gotoRow{ // S132
		-1, // S'
		-1, // Rules
		-1, // Rule
		-1, // Action
		-1, // Type
		-1, // AtomicAction
		-1, // Target
	},
}
